<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Coupa.Supplier.Domain\Coupa.Supplier.Domain.csproj" />
    <ProjectReference Include="..\Coupa.Supplier.Shared\Coupa.Supplier.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="*" />
  </ItemGroup>
</Project>
