<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Coupa.Supplier.Application\Coupa.Supplier.Application.csproj" />
    <ProjectReference Include="..\Coupa.Supplier.Infrastructure\Coupa.Supplier.Infrastructure.csproj" />
    <ProjectReference Include="..\Coupa.Supplier.Shared\Coupa.Supplier.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="*" />
  </ItemGroup>
</Project>
